### ISSUE TITLE
Support es2016 arrays include

### ISSUE THREAD

**Issue by dougpool** [dherges/ng-packagr#467]
## Type of Issue

```
[ ] Bug Report
[X ] Feature Request (Help Request...maybe I just don't know how to make it work)
```

## Description

I'm trying to use the tool to package up an ng module that makes use of Array.includes, however when I run the tool, I get the error:

Property 'includes' does not exist on type 'any[]'.

If I remove the line, it build/packages as expected. If I manually go into the tsconfig.ngc.json  and change the lib to be es2016 (es2015 is the lib that appears in the tsconfig.nfc.json file), then it also builds the package.

` "lib": ["dom", "es2016"]`

I just feel like I'm not doing this correctly or in a supported way. Please advise.

Update: Maybe the es2016 array features are supported by APF. Was reading the https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview and everything seems to revolve around es2015 in their examples. But still, couldn't the es2016 lib be used as input with es2015 output? Not sure if this is possible or not for APF.

#### How To Reproduce

Clone the ng-packaged example, add the lines

`export class FooComponent {
  constructor() {
    const someArray = [];
    someArray.includes('');
  }
`

to foo.component.ts

run

`
npm run build:lib
`

#### Expected Behaviour

Ideally, this would be packaged correctly without the error (array includes error) above.
 
Also, the tested example was with ng-packagr: 2.0.0-rc.9, but I'd like it to work with 1.6.0/Angular 4 as well.

#### Version Information

```
ng-packagr: 2.0.0-rc.9
@angular/*: 5.1.0
typescript: 2.5.3
rxjs: 5.4.2
node: 9.0.0
npm/yarn: 5.6.0
```

**Comment by dherges** [comment]
Duplicate of #354 

A pull request for that is very welcome!

**Comment by dherges** [comment]
Hi @dougpool,

I am closing this issue as it's really a duplicate of the "Language level support" issue. Whether the PR is vor v1 or for v2, either of them is appreciated!
