### ISSUE TITLE
Error StaticInjectorError[ViewContainerRef] when having *ngIf or *ngFor  // Solution: `--preserve-symlinks` 

### ISSUE THREAD

**Issue by doenikoe** [dherges/ng-packagr#304]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
When I am using either *ngIf or *ngFor in my template I got this error message: `StaticInjectorError[ViewContainerRef]`. Any ideas why this happen?

<img width="645" alt="screen shot 2017-11-22 at 5 48 52 pm" src="https://user-images.githubusercontent.com/1280444/33124018-604beca0-cfae-11e7-9c1c-1a731a4e9ebd.png">

#### How To Reproduce
1. Create a component `footer.component.ts`
2. Add *ngIf in `footer.component.html`
3. Run `ng-packagr -p ng-package.json` and `npm publish`
4. Install on new Angular 5 app (`npm install`)
5. Run my Angular 5 App `ng serve`

Here is my code:

**footer.component.ts**
```
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {
  @Input() isTrue: boolean;

  constructor( ) { }

  ngOnInit() { }
}
```

**footer.component.html**
```
<footer>
    <h2 *ngIf="isTrue">Hello</h2>
</footer>
```
#### Expected Behaviour
Should not error

#### Version Information

```
ng-packagr: ^1.6.0
node: v7.6.0
@angular: v5.0.2
rxjs: v5.5.2
zone.js: v0.8.18
```

**Comment by dherges** [comment]
#299 

Please, use the `ng-packagr@next` (2.0.0 release candidates) and typescript `2.4.x`. Does it disappear?

**Comment by dherges** [comment]
Hi @doenikoe,

the error is reproducible in the integrationt ests of ng-packagr by running `ng serve` in the Angular CLI consumer app.

If you can figure out what is causing the Angular DI to throw the `StaticInjectionError`, it's going to help!

**Comment by dherges** [comment]
jvandemo/generator-angular2-library#240

angular/angular#20598

**Comment by jcjolley** [comment]
So, my team found a horrible fix for this issue:
1. Create a new project with the Angular CLI.
2. Copy over all of the dependencies from its package.json to your package.json
3. Delete your node_modules folder and your package-lock.json
4. npm install

**Comment by dominique-mueller** [comment]
As mentioned in https://github.com/dominique-mueller/angular-package-builder/issues/38, using the `--aot` or `--preserve-symlinks` flag on `ng serve` probably solves this issue (which occurs when installing the library via a local directory instead of remotely).

**Comment by vapits** [comment]
Same here:
![image](https://user-images.githubusercontent.com/8594758/35279815-7d75d3ba-004e-11e8-99c8-123735a6ea05.png)

:/

**Comment by dominique-mueller** [comment]
Have you tried the `--preserve-symlinks` flag?

**Comment by vapits** [comment]
@dominique-mueller tried with `--preserve-symlinks`, tried with `--aot` in general tried a lot :P

**Comment by dherges** [comment]
Hi all,

please check and confirm whether `--preserve-symlinks` solves the issue as it does for the original error (`StaticInjectorError`). Should it not in your case, please open a separate issue.

**Comment by vapits** [comment]
@dherges it does not. Why to spam the issues with duplicate items?

**Comment by dskyyy** [comment]
Still facing with StaticInjectionError even with --preserve-symlinks flag. Unfortunately it’s not the solution for *ngIf / *ngFor case.

**Comment by dherges** [comment]
Please make an issue with a publicly accessible repro.

**Comment by rivamadan** [comment]
I have the similar error with with angular 5.2.0. `--preserve-symlinks` didn't work and upgrading ng-packgr to `2.0.0-rc12` didn't work. We just have a simple component using `ngIf` and `ngClass`.

This is the error:
```
ERROR Error: StaticInjectorError(AppModule)[NgClass -> IterableDiffers]:
 StaticInjectorError(Platform: core)[NgClass -> IterableDiffers]:
   NullInjectorError: No provider for IterableDiffers!
```

**Comment by vapits** [comment]
Yup same here even a simple `*ngIf` gives this error.

**Comment by vapits** [comment]
@doenikoe did you get this issue fixed?

**Comment by SravanKumarNangunoori** [comment]
Did anyone solve the issue ?? seems --preserve-symlinks also does not work

**Comment by vapits** [comment]
@SravanKumarNangunoori did you manage to make it? It doesn't seem to work still with latest version.

**Comment by stephanmullerNL** [comment]
I have a similar issue when trying to use `[ngClass]` in a module that I import to another module. Using `--preserve-symlinks` doesn't solve it. When I use `--aot` I get an error message:

```
ERROR in ../sam-site/src/app/shared/shared.module.ts(5,2): Error during template compile of 'SharedModule'
  Function expressions are not supported in decorators in 'NgModule'
    'NgModule' contains the error at @angular/core/core.ts(194,31)
      Consider changing the function expression into an exported function.
```

I'm not familiar enough with Angular to know what this means or what to do with it, maybe someone has an idea where to look?

**Comment by sumitkatiyar** [comment]
first check u have defined all the service in the  app.module.ts provider 
like -    providers: [UserService, AuthService, Interceptor, TokenStorage],

**Comment by giacomoalonzi** [comment]
Same error here `StaticInjectorError(Platform: core)[NgClass -> IterableDiffers]` and `--preserve-symlinks` seems not work. Any hint?

**Comment by BMLande** [comment]
i dont whats it getting wrong but for me following solution works (i facing this in anguiar5)
add in angular-cli.json
"defaults": {
    "styleExt": "css",
    "component": {},
    "build": {
        "preserveSymlinks": true
    }
}

- delete node modules
- npm install
- ng serve
https://github.com/jvandemo/generator-angular2-library/issues/240 with the help oh this ,

this may help ........... :-)

**Comment by vapits** [comment]
UPDATE: I manage to solve the issue by updating both my lib and my app that uses the lib to Angular 5.2.8 (it works with 5.2.9 also) and angular cli to  1.7.3.
No preserveSymlinks or any other configuration is needed!

**Comment by nmarra** [comment]
@vapits Could you link an example project with this working?  I'm currently still having issues using the Angular 5.2.8 and cli 1.7.3.   Maybe there is another package that needs to be a specific version or you have a specific angular/webpack config?  My main app will not dynamically load the lib with *ngIf, but loads fine without an *ngIf.

**Comment by peturh** [comment]
This happened for me as well.

1. I created an Angular library, a custom checkbox called `my-checkbox`.
2. I run `yarn link` in the `my-checkbox` dist folder.
3. I run `yarn link my-checkbox` inside my "real" app folder.
4. I add `import { MyCheckbox } from `my-checkbox`
5. I build the the app with `ng build --watch`

I get this warning from `angular-cli`

    WARNING in ../bim-checkbox/node_modules/@angular/core/fesm5/core.js
    4996:15-36 Critical dependency: the request of a dependency is an expression

I get this error runtime from browser:
```
ERROR Error: StaticInjectorError(AppModule)[NgClass -> KeyValueDiffers]: 
  StaticInjectorError(Platform: core)[NgClass -> KeyValueDiffers]: 
    NullInjectorError: No provider for KeyValueDiffers!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:1060)
    at resolveToken (core.js:1298)
    at tryResolveToken (core.js:1242)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1139)
    at resolveToken (core.js:1298)
    at tryResolveToken (core.js:1242)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1139)
    at resolveNgModuleDep (core.js:8377)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:9065)
    at resolveDep (core.js:9430)
```
**Solved by running `ng build --watch --preserve-symlink`**

**Comment by KamilPolanowski** [comment]
sorry for commenting in closed issue but some of you guys going to love me for this and how trivial this is;
long story short - the module imports order is crucial;
please, refer to this article: https://blog.angularindepth.com/avoiding-common-confusions-with-modules-in-angular-ada070e6891f

**Comment by kyleconkright** [comment]
I was working on this and I don't use the angular cli. The answer was very simple for me. Remember to remove your library's dependencies before installing into your main app.

**Comment by samuel44ase** [comment]
> #299
> 
> Please, use the `ng-packagr@next` (2.0.0 release candidates) and typescript `2.4.x`. Does it disappear?

npm install ng-packagr
then npm install
