### ISSUE TITLE
v3rc5 incorrectly compiles lambda-with-a-comment.

### ISSUE THREAD

**Issue by wardbell** [dherges/ng-packagr#901]
The `v3.0.0-rc.5` release broke my library by incorrectly compiling a lambda (arrow-function) with a comment in it.

Here's the TS example:

```
    Object.keys(metadataMap || {}).forEach(entityName =>
      // The entity type name should be the same as the map key
      this.registerMetadata({ entityName, ...metadataMap[entityName] })
    );
```
It compiled to confused JavaScript that put a `return` statement on its own line, aborting the function before it could do its job. See "Full discussion" below for details.

This is new misbehavior in `v3.0.0-rc.5`. This compiled correctly in `v3.0.0-rc.2`

The "tl;dr" for everyone reading this is **do not embed comments in unbraced arrow functions**, at least until this is fixed.

Coincidentally, `v3.0.0-rc.5` corrects a _different compilation error_ that existed in `v3.0.0-rc.2`, one that cause Angular applications using the library to fail in production builds, as reported in [_ngrx-data_ issue 156](https://github.com/johnpapa/angular-ngrx-data/issues/156).

Merely switching between `rc2` and `rc5`, with no other code changes, is sufficient to reveal the compilation errors and differences (rc2: bad production build but good lamba; rc5: "good" production build after working around bad lambda).

### Editorial Comment

These inexplicable perturbations are wrecking havoc on my schedule and my confidence. There is so much magic here and it is exceedingly difficult to know what is going on

### Full Discussion

The [following method with lambda](https://github.com/johnpapa/angular-ngrx-data/blob/master/lib/src/entity-metadata/entity-definition.service.ts#L77-82) appears in the [beta.4 release of _ngrx_data_](https://github.com/johnpapa/angular-ngrx-data/releases/tag/6.0.0-beta.4).

```
  /**
   * Register an EntityMetadataMap.
   * @param metadataMap - a map of entityType names to entity metadata
   *
   * Examples:
   *   registerMetadataMap({
   *     'Hero': myHeroMetadata,
   *     Villain: myVillainMetadata
   *   });
   */
  registerMetadataMap(metadataMap: EntityMetadataMap = {}) {
    Object.keys(metadataMap || {}).forEach(entityName =>
      // The entity type name should be the same as the map key
      this.registerMetadata({ entityName, ...metadataMap[entityName] })
    );
  }
```

>I concede that it is rare to break up a brace-less arrow function with a comment. I swept my code base and found only one other example where I did this. But it is allowed and you can see that it should work in the TypeScript playground.

<hr>

It compiled to JS as expected with  `v3.0.0-rc.2`,

```
   /**
     * Register an EntityMetadataMap.
     * @param {?=} metadataMap - a map of entityType names to entity metadata
     *
     * Examples:
     *   registerMetadataMap({
     *     'Hero': myHeroMetadata,
     *     Villain: myVillainMetadata
     *   });
     * @return {?}
     */
    EntityDefinitionService.prototype.registerMetadataMap = function (metadataMap) {
        var _this = this;
        if (metadataMap === void 0) { metadataMap = {}; }
        Object.keys(metadataMap || {}).forEach(function (entityName) {
            // The entity type name should be the same as the map key
            return _this.registerMetadata(Object.assign({ entityName: entityName }, metadataMap[entityName]));
        });
    };
```

<hr>

But when I updated to  `3.0.0-rc.5`, it did the following to that same method-cum-lambda:

```
  EntityDefinitionService.prototype.registerMetadataMap = /**
     * Register an EntityMetadataMap.
     * @param {?=} metadataMap - a map of entityType names to entity metadata
     *
     * Examples:
     *   registerMetadataMap({
     *     'Hero': myHeroMetadata,
     *     Villain: myVillainMetadata
     *   });
     * @return {?}
     */
    function (metadataMap) {
        var _this = this;
        if (metadataMap === void 0) { metadataMap = {}; }
        Object.keys(metadataMap || {}).forEach(function (entityName) {
            // The entity type name should be the same as the map key
            return 
            // The entity type name should be the same as the map key
            _this.registerMetadata(__assign({ entityName: entityName }, metadataMap[entityName]));
        });
    };
```

**The `return` statement is sitting on a line by itself!**  That causes the function to exit silently without doing the work that the compiler moved to the following line.

The comment formatting madness is an afterthought.

<hr>

### Workaround

I moved the comment up one line and out of the arrow-function. It went from this ...

```
    Object.keys(metadataMap || {}).forEach(entityName =>
      // The entity type name should be the same as the map key
      this.registerMetadata({ entityName, ...metadataMap[entityName] })
    );
```
... to this

```
    // The entity type name should be the same as the map key
    Object.keys(metadataMap || {}).forEach(entityName =>
      this.registerMetadata({ entityName, ...metadataMap[entityName] })
    );
```

And now it produces proper JS (leaving aside how it moved the doc comments)

```
    EntityDefinitionService.prototype.registerMetadataMap = /**
     * Register an EntityMetadataMap.
     * @param {?=} metadataMap - a map of entityType names to entity metadata
     *
     * Examples:
     *   registerMetadataMap({
     *     'Hero': myHeroMetadata,
     *     Villain: myVillainMetadata
     *   });
     * @return {?}
     */
    function (metadataMap) {
        var _this = this;
        if (metadataMap === void 0) { metadataMap = {}; }
        // The entity type name should be the same as the map key
        Object.keys(metadataMap || {}).forEach(function (entityName) {
            return _this.registerMetadata(__assign({ entityName: entityName }, metadataMap[entityName]));
        });
    };
```

**Comment by alan-agius4** [comment]
This is an Angular Compiler bug, 

I open an issue: https://github.com/angular/angular/issues/24092

**Comment by wardbell** [comment]
Sorry for your trouble. Sorry for mine. Closing as not your issue
